### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by cjvanlissa** [aaronpeikert/repro-tutorial#104]
@aaronpeikert I've read the manuscript and provided copious notes. My main point of feedback cannot be provided inline, so I will provide it here. I think that, aside from incorporating the

**Comment by brandmaier** [comment]
I am afraid that some of your text got lost, @cjvanlissa.

**Comment by cjvanlissa** [comment]
I can't remember what this was regarding! It's possible that @aaronpeikert and I had a phone call right when I was opening this issue, and that I may have absentmindedly opened it.

**Comment by cjvanlissa** [comment]
Either way, Aaron knows that my main comment is that the structure should be revised; probably something like:

1) General introduction of the problem and proposed solution
2) Exposition of the techniques used as part of the solution
3) Tutorial demonstrating those techniques

Currently, these three themes are intermixed.

My second main comment was that attention should be paid to tell people only the information they need to know for the tutorial (e.g., skip examples using SEM because a large part of the readership won't know SEM), and that new information should be presented at the right time. For example, I believe that Issues and Pull Requests were introduced before GitHub was introduced. Several cases like that appear. This is confusing to any readers not yet familiar with the techniques.
