### ISSUE TITLE
reorder introduction

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#110]
Introduction is ordered:

1. Version control
2. Dynamic document creation
3. Software management
4. Dependency tracking

But should be:

1. Version control
2. Dynamic document creation
3. Dependency tracking
4. Software management

**Comment by cjvanlissa** [comment]
Or even:

1. DDC
2. Dependency
3. Software management
4. Version control (because what are you version controlling? All of the above.

**Comment by aaronpeikert** [comment]
I see your argument. I would like to have tutorial and theoretical structure aligned. And my rational for the tutorial is:
First you create an RProject with version control (1). You write your RMarkdown (2). Then you add the repro metadata.
automate() creates the Makefile and Dockerfile. You can either run make locally.(3) or within docker (4).
Does anyone see a more didactically reasonable approach?

**Comment by cjvanlissa** [comment]
That'll work.
