### ISSUE TITLE
remove historical perspective on sweave

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#111]
I appreciate the historical overview of the development of literate programming in R, but fear that it may lead to confusion because it introduces a) to many names we ultimately do not use b) reminds researcher of latex (which many have mixed feelings about).

**Comment by cjvanlissa** [comment]
Agreed, this lines up with my general advice to introduce only those tools needed for the tutorial

**Comment by aaronpeikert** [comment]
218fa1e640341fbcdb
