### ISSUE TITLE
cite "Many Analysts, One Data Set"

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#122]

**Comment by aaronpeikert** [comment]
nah

**Comment by cjvanlissa** [comment]
This is a great justification for preregistration as code (in fact, their latest project looks at preregistration), and also for emphasizing researcher degrees of freedom

**Comment by aaronpeikert** [comment]
Ah now I see, the section where I wanted to cite it was lost in some merge :imp: #130
