### ISSUE TITLE
find good tutorial on simulating data

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#199]

**Comment by brandmaier** [comment]
What about this?
https://www.tandfonline.com/doi/abs/10.1207/S15328007SEM0802_7?casa_token=v9oWEiKIlCoAAAAA:ba0UtDKSjESM5N3pBZh6TD0HqjmIZBc21KnTY1bOOIN3H7_h2UfwQzt_91z-GvxOy5oeS92ZiQc-rTk

**Comment by brandmaier** [comment]
und das https://www.tandfonline.com/doi/abs/10.1207/S15327906MBR3502_1?casa_token=eAQw0ie2aIsAAAAA:XGSMiL1IpMeSEhNgUNC6DOhhJu0HnQ_DYY6wOy6uFPoOk6yZwpF6H0fb9rPfRnrqP9H2dIJ3s_BZR2w

**Comment by aaronpeikert** [comment]
Both are great! Due to lack of time, these will have to suffice. Maybe if we come across some other (not focused on SEM) we include them then.

**Comment by demianJK** [comment]
Maybe this will help: https://onlinelibrary.wiley.com/doi/full/10.1002/sim.8086

**Comment by aaronpeikert** [comment]
@demianJK Great, we will include it!
