### ISSUE TITLE
describe how articles are actually submitted

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#215]
possibly refer to papaja

**Comment by cjvanlissa** [comment]
I think it's worth emphasizing that many people, including us authors, are already submitting articles written in Rmarkdown. We can address the comment further by providing some guidance (e.g. indeed papaja) on how to go about this.

**Comment by brandmaier** [comment]
yes to both. Mention that articles can be rendered into PDF/DOC/etc.. and that some journals start to accept RMarkdown. eLife is a great example of how dynamic documents can be integrated into a submission/revision workflow.
