### ISSUE TITLE
discuss data privacy concerns when publishing data

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#217]

**Comment by cjvanlissa** [comment]
This is a really big one. Even our university's legal team is at odds with our data management office about this. I'm not sure we can reconcile it in this paper - but maybe link to a paper that addresses the tradeoff between reproducibility and privacy concerns?

**Comment by aaronpeikert** [comment]
I agree. And honestly, it is out of scope. Of course interesting and relevant, but nevertheless not aligned with the main aim of the paper.

**Comment by brandmaier** [comment]
Out of scope. This is not a problem of PAC but a problem of open science in general. Nothing we can solve in this paper.
