### ISSUE TITLE
strengthen the case that one can deviate from the preregistration if it is obvious to the reader

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#219]
Reviewer I argue that contrary to agile software development PAC requires researchers to foresee everything.

**Comment by cjvanlissa** [comment]
Yes; I think this can be a feature, not a bug: Emphasize that necessary changes can be made, and documented in the commit messages AND a changelog.txt file. Example: https://github.com/cjvanlissa/manyanalysts_religion/compare/1f2a6bd..e38391d

**Comment by brandmaier** [comment]
Seems to be a duplicate of #237.
