### ISSUE TITLE
how to scale `planned_analysis()` to multiple hypothesis/tests/models

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#220]

**Comment by cjvanlissa** [comment]
Add an argument planned_analysis(which = "name") or planned_analysis(research_question = "name") or something similar?

**Comment by cjvanlissa** [comment]
If no argument is provided, it could just number them based on the metadata

**Comment by brandmaier** [comment]
I had the same question when I was reading this the first time. I understood this as a mere suggestion not necessarily a proposed standard? So it could be done in various other ways - but probably it's a good idea to give a suggestion of best practice in your view, @aaronpeikert .

**Comment by aaronpeikert** [comment]
Yes, it was merely a suggestion on how one could structure it. `planned_analysis()` is a user-written function but I expect most users prefer to write a script.
Because many researchers number their hypothesis it would be most natural to name the functions/scripts according to this numbering scheme:

* planned_analysis_1b()

or

* planned_analysis_2_1.R

**Comment by brandmaier** [comment]
I suggest to clarify that this is not a genuine repro-function (like automate etc) but really just a suggestion how to structure your analysis in code.
