### ISSUE TITLE
connecting Git and GitHub is too difficult

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#222]

**Comment by cjvanlissa** [comment]
Consider using gert for this; it's pretty foolproof.

**Comment by aaronpeikert** [comment]
We already rely on gert for this. (OK actually usethis relies on gert + gh + gitcreds).

I also find it a bit clunky so maybe I reexport this function from usethis and later adapt it to be more user-friendly.
