### ISSUE TITLE
conventional preregistrations have some advantages

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#228]

**Comment by aaronpeikert** [comment]
Sorry, read this section again! Reviewer 2 raises some good points:
* researcher degrees of freedom can not always be reduced to if-else statements
* preregistrations often contain more detailed information than the manuscript

**Comment by cjvanlissa** [comment]
If preregistration templates contain something MORE than a paper would, maybe we should consider what we can learn from preregistration templates that can help us improve our manuscripts? In other words: If prereg templates address something that normal papers don't, we should consider just putting that into normal papers (or at least into the PAC).

**Comment by brandmaier** [comment]
good point. Also, you can easily have a reproducible PAC Appendix, which contains all extra details.

**Comment by aaronpeikert** [comment]
@cjvanlissa this highlights a core issue of scientific comunication. Most articles simply do not contain enough information to replicate.
@brandmaier  The appendix idea is a really practical response.

**Comment by aaronpeikert** [comment]
related #244
