### ISSUE TITLE
strip PAC to the essentials

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#229]
consider removing:

- [ ] rules for writing a preregistration
- [ ] rules for academic writing in general
- [ ] power simulations

**Comment by cjvanlissa** [comment]
I wouldn't remove power simulations completely, maybe just mention them as an opportunity afforded by PAC, and provide a reference

**Comment by brandmaier** [comment]
yeah, let's keep power simulations!! Shorten the other parts as you see fit or replace with appropriate citations.

**Comment by aaronpeikert** [comment]
I guess these comments all relate to the introduction to "What you need to know before writing a PAC".
I have carefully reviewed this section and agree that one could remove the introduction. The introduction was meant to argue for the benefits of moving the writing of the manuscript before data collection and data simulation for planning a study.
Nevertheless, I decided to keep this section because PAC was borne out of exactly the frustration I feel routinely in consulting on studies **after** data collection and my ideas on how to prevent preventable mistakes in study planning.
I appreciate that the reviewer does not see the relevance and take it that there is room for improving this section.
But I am at a loss at how.

I would greatly appreciate it if either of you @brandmaier, @cjvanlissa could read the section and give me some hints on how to improve it. Or, as always, you are more than welcome to change things.
