### ISSUE TITLE
emphasize the relevance of seeds for reproducibility

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#230]

**Comment by cjvanlissa** [comment]
Sometimes even seeds are not sufficient, e.g. with paralellization. Maybe also acknowledge that in some cases exact reproducibility is just hard to achieve and mention the concept of Monte Carlo error?

**Comment by brandmaier** [comment]
The parallelization/seed problem has efficient solutions nowadays (cf. the future package). Aaron has put a lot of thought into this already. Should be easy to address. Also, please point to Peikert & Brandmaier (https://qcmb.psychopen.eu/index.php/qcmb/article/download/3763/3763.html?inline=1), where we discuss similar issues.

**Comment by aaronpeikert** [comment]
Remember we had a long section on this in the first draft (including parallelization) and cut it out as off-topic. Let's bring it back to life.

**Comment by brandmaier** [comment]
OK! If too long, consider shortening it a little.
