### ISSUE TITLE
explain how this workflow is suitable for multi site studies

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#234]

**Comment by cjvanlissa** [comment]
Maybe mention the possibility of running docker on a server, or dockerhub here? Those seem useful for multi-site studies

**Comment by brandmaier** [comment]
Yes, I think direct and indirect code re-use is a big bonus. This applies to making both analyses as well as presentation of results (ie, graphs) more streamlined across sites.

**Comment by aaronpeikert** [comment]
I was really surprised that two reviewers anticipated problems in multisite studies. I actually was convinced that this reproducibility standard and PAC were uniquely suited for multi-site research projects.
My line of reasoning was that the high standardisation and possible reuse are advantages that are pronounced in those settings.
I have to think about this a while longer.

**Comment by brandmaier** [comment]
At this point in time, the utility for multi-site studies is simply a claim. We have developed this workflow as a general workflow for collaborative projects, so I expect them to work well also for multi-site studies.  I think we should argue that we expect them to work well in multi-site studies but that the workflow has yet to stand the test of time.
