### ISSUE TITLE
argue for pre-registration after data collection

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#238]

**Comment by cjvanlissa** [comment]
I believe this reference might help:

Weston, S. J., Ritchie, S. J., Rohrer, J. M., & Przybylski, A. K. (2019). Recommendations for Increasing the Transparency of Analysis of Preexisting Data Sets. Advances in Methods and Practices in Psychological Science. https://doi.org/10.1177/2515245919848684

**Comment by brandmaier** [comment]
This is a tricky issue. I would be inclined to put more trust into a preregistration if there was no data available to begin with -- but even with current preregistrations, who is able to judge whether the data have been collected already or not? Anyhow, I would suggest to phrase it in a way that you are supposed to preregister first and then collect your data but, with secondary data analyses, we can get at more realistic fake data by shuffling, synthetic data, etc. (add citation that @cjvanlissa suggested).

**Comment by aaronpeikert** [comment]
Preregistration is not a tool to prevent fraud. If a researcher states that they have not analyzed the data, we have to believe that.
I do not see how a timestamp in a file changes the deductive nature of testing the theory, it is the knowledge that fundamentally changes this. Of course, researchers can intentionally "ruin the surprise" by looking at the results and then preregister but at the same time, they can maliciously simulate data and fake all results *after* propper preregistration. Both is grave scientific misconduct and simply lying.

The question is, can researchers spoiler themselves unintentionally?

**Comment by aaronpeikert** [comment]
Ok I admit  I am guilty of ignoring this distinction:

Preregistration seeks to reduce “researcher degrees of freedom” [4] in the execution of a planned study by limiting the number of decisions to be made after data has been collected, which could bias the reported results.

**Comment by brandmaier** [comment]
> Preregistration is not a tool to prevent fraud. 
Yes, this is an important point.

**Comment by cjvanlissa** [comment]
@aaronpeikert the point here is not precluding intentional fraud, but encouraging best practices. You have to consider that in many fields, data collection is distinct from the planning of individual studies. Developmental psychology is a key example; collecting longitudinal datasets takes sometimes decades. Meanwhile, individual people are preparing data use applications. It's great if these are preregistered. Of course, prior exposure (direct or indirect) to the data should be disclosed - but the quality of research will *still* be improved if researchers preregister their hypotheses.

**Comment by aaronpeikert** [comment]
Yes, I know and I could not agree more! That is why I said preregistration can not prevent fraud because they have a different function. 
Considerations on how to "game" preregistration are often used as an argument against preregistration and especially against preregistration after data collection. But I simply think it is a misguided argument. Of course, you can misuse preregistration after data collection but this is beside the point because if we were to assume malicious researchers we would have to reconsider everything in research not only open science.
