### ISSUE TITLE
complete author information

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro-tutorial#44]
currently author affiliations are missing. Please add.

**Comment by brandmaier** [comment]
Also add Caspar, please.

**Comment by aaronpeikert** [comment]
@brandmaier @cjvanlissa Could you check if the information about you are correct:

https://github.com/aaronpeikert/repro-tutorial/blob/9d8e3b8aee45c4694d4e57b6421f0b6a375173ef/manuscript.Rmd#L3-L27

**Comment by brandmaier** [comment]
Correct!

**Comment by cjvanlissa** [comment]
Correct!

**Comment by aaronpeikert** [comment]
Wait, @cjvanlissa ! Is it "Caspar J. Van Lissa" or "Caspar J. van Lissa"?

**Comment by cjvanlissa** [comment]
As per Dutch spelling, it's Caspar J. van Lissa, and also Van Lissa, Caspar J.

**Comment by cjvanlissa** [comment]
But to be concrete: Just put Caspar J. Van Lissa

**Comment by aaronpeikert** [comment]
So I'll close? (its correct than is it?)

**Comment by cjvanlissa** [comment]
Yes!
