### ISSUE TITLE
cite something about the ambiguity of natural language vs. formal language

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#53]
https://github.com/aaronpeikert/repro-tutorial/blob/4fca9efc4a532540f5ea475ba42d6078bc25f584/manuscript.Rmd#L482

**Comment by Maximilian-Stefan-Ernst** [comment]
Unfortunately not - of course there is literature about the differences between formal language and nl, but you seem to look for something that is specifically about turning natural language into code. Maybe this can be a good starting point:
Abelson, H., & Sussman, G. J. (1996). Structure and interpretation of computer programs (p. 688). The MIT Press.

There is a paragraph about parsing natural language.
