### ISSUE TITLE
cite [`faux`](https://debruine.github.io/faux/index.html)

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#64]

**Comment by Maximilian-Stefan-Ernst** [comment]
Don't know where to put it, but added it to packages.bib

**Comment by aaronpeikert** [comment]
@Maximilian-Stefan-Ernst packages.bib is automatically generated and is reserved for packages actually used and therefore availible in the Dockerimage.

https://github.com/aaronpeikert/repro-tutorial/blob/ae786a52e5c83b391c7bf5027264fc9bc6350dae/manuscript.Rmd#L1333-L1334

Just move it to references.bib, I know not the most intuitive nameing scheme. Feel free to change that soo.

Thanks for helping out!
