### ISSUE TITLE
add a table of all major repro functions

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro-tutorial#68]
Should look about like this:

R command | Functionality | When to use
----------------------
automate() | Parse Markdown meta-data and create Docker and Make files | Run whenever you added a new R package or added a data file
check_github() | Checks whether git is installed and working properly | Run before the first use of `repro`
check_docker() | "
check_make() | "
rerun() | Run whenever ....

**Comment by brandmaier** [comment]
I think this is really helpful once you have read the manuscript once and then just a need a quick reminder of what functions the package actually provides. What other functions am I missing?

**Comment by aaronpeikert** [comment]
:100: Thats about it.

**Comment by aaronpeikert** [comment]
closed in #72
