### ISSUE TITLE
non-reproducibility

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro-tutorial#78]
If I build repro-tutorial on my local machine, the following code breaks (I want to understand why this happens):
```{r}
# unfortunately css selectors won't work for pdf so we'll use png instead
readme <- here::here("images", "readme.png")
webshot2::webshot("https://github.com/aaronpeikert/repro-tutorial/",
                  file = readme,
                  vwidth = 1920, # height & width are not resolution
                  vheight = 1080, # but what website thinks the browser size is
                  selector = "div#readme",
                  zoom = 2) # higher resolution
```

The error is:

```
Error in onRejected(reason) : code: -32601
  message: 'Inspector.enable' wasn't found
```

Why does this work in the container but not locally? Also, the earlier use of webshot (idea image) does work!

**Comment by aaronpeikert** [comment]
I actually have trouble with webshot2 (because my chrome installation requires `Sys.setenv(CHROMOTE_CHROME = "google-chrome-stable")`)

    webshot2::webshot("https://github.com/rstudio/shiny")

**Comment by aaronpeikert** [comment]
Are you sure that the use of webshot works before? It is cached after all...

**Comment by brandmaier** [comment]
<img width="407" alt="Screenshot 2021-05-18 at 09 02 11" src="https://user-images.githubusercontent.com/116031/118606478-c069f600-b7b7-11eb-9666-0ef4a463085c.png">

on
```
R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit
```
with a local Chrome installation.

**Comment by aaronpeikert** [comment]
This is the culprit:

https://github.com/rstudio/chromote/issues/44

Try installing the newest (they fixed it yesterday) version of chromote:

    remotes::install_github("rstudio/chromote@4bce61c")

**Comment by brandmaier** [comment]
Hm. What does this mean for the reproducibility guarantee.. obviously our approach failed here. What is the solution? Do we have to manually fix all downstream dependencies at a given version? I am not sure I fully understand what broke reproducibility here.

**Comment by aaronpeikert** [comment]
@brandmaier I think it highlights the need for containers. Your local chrome installation doesn't have the API required, which forces you to update either chrome or the package webshot, but the dockerized version works just fine. 

Please close when you agree.
