### ISSUE TITLE
container build failed

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro-tutorial#79]
On my machine, I get this after `make -B`:

```
Quitting from lines 1275-1276 (manuscript.Rmd) 
Error: 'git_commit_id' is not an exported object from 'namespace:gert'
```

**Comment by aaronpeikert** [comment]
I might be that Docker reuses some chache that it should not reuse.

Try `make rebuild` to build docker without cache.

**Comment by brandmaier** [comment]
Hm. What does this mean for the reproducibility guarantee.. obviously our approach failed here. What is the solution? Do we have to manually fix all downstream dependencies at a given version? I am not sure I fully understand what broke reproducibility here.

**Comment by aaronpeikert** [comment]
andreas reported that this works now
