### ISSUE TITLE
remove empty sections

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro-tutorial#82]
I recommend removing all empty sections now and finish what we have. That is, delete this:
5.3 Archiving Docker
5.4 Archiving Data
6 Checklist

Instead of (6) reference the new checklist table once again in the discussion.

**Comment by aaronpeikert** [comment]
I agree though I would like to keep Archiving Docker (just to mention `make  save-docker`). Because I see this as the crucial breaking point of the workflow.

**Comment by brandmaier** [comment]
OK, then add those sections that you want to have. I would like to get the manuscript into a form, such that we do not add sections after Friday.
