### ISSUE TITLE
reproduction of this paper will take ages for most people

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#90]
@brandmaier @cjvanlissa The simulation study takes a long time (I think it fits a few million sems).
https://github.com/aaronpeikert/repro-tutorial/blob/3748bd0d5c2d7641eb274397a2f4c3df525018fd/README.Rmd#L29

**Comment by brandmaier** [comment]
With the simpler example, I think this is obsolete.
